### PR TITLE
Fix cannot use gamePin (type string) as type int and add gopass to installation section in README

### PR DESCRIPTION
**Pull request by elisaado**

### CODE REVIEW

**Comment by unixpickle** [comment]
What are you doing? The gamePin error you are seeing shouldn't be happening. It almost looks like you updated some files in the repo, but not the main kahoot library, where [NewConn](https://github.com/unixpickle/kahoot-hack/blob/837ffedbc5ed971e9460d47bbe08fade1fa9056f/kahoot/conn.go#L37) now takes a string instead of an int.

**Comment by elisaado** [comment]
NewConn should take a string, but it did not which caused the error (gamePin is a string), I am not sure why this is happening, but it also did with a fresh clone of kahoot-hack

I will try it in a fresh docker with no other Go packages to see if that was a problem

**Comment by elisaado** [comment]
This seems very strange

Edit:
NewConn takes gameId as a string, but not gamePin

**Comment by elisaado** [comment]
What am I doing, indeed.

Apparently, I had an older copy of kahoot-hack in my GOROOT which wanted gameId as an int.

**Pull request closed without merging**
