### PR TITLE
Add delay between connections and statistics to kahoot-rand, fix websocket error

### PR DESCRIPTION
**Pull request by Arccotangent**
The purpose of the delay between connections is so you don't flood the site with hundreds of connections at once. I've had a problem when using large amounts of bots without the delay and this seems to fix it.

The statistics are there because I thought they might be useful to some users.

The statistics display:
```
go run main.go 236604 bot 42
Bots Entered:  42
Terminate this program to stop the automatons...
-----STATISTICS-----
Question Number:  1
Answer Count:  2
Answer 0:  20
Answer 1:  22
Answer 2:  0
Answer 3:  0
-----STATISTICS-----
Question Number:  2
Answer Count:  3
Answer 0:  14
Answer 1:  15
Answer 2:  13
Answer 3:  0
-----STATISTICS-----
Question Number:  3
Answer Count:  4
Answer 0:  17
Answer 1:  9
Answer 2:  10
Answer 3:  6
```

Feel free to suggest improvements!

### CODE REVIEW

**Comment by unixpickle** [comment]
These are both good ideas. I am surprised I never thought to add statistics to kahoot-rand. The delay is probably helpful, although it depends on the client running the Kahoot host. If your teacher's computer is particularly slow (probably a crappy windows machine), then I can imagine a timeout helping. On my Chromebook, for instance, Chrome started lagging if I joined with 50 clients in rapid succession.

There are a few changes you should make to this pull request before it is merge-able:

 * The changes you made to kahoot-flood/main.go are unnecessary and should be removed.
 * The client delay should be an optional command line argument rather than a hard-coded constant. This way, users can specify the delay easily.
   * For instance, the command-line usage might become `rand <pin> <prefix> <count> [delay]`.
 * You should format the code with `gofmt`. The code on line 80 of rand.go is indented incorrectly, indicating that you did not use `gofmt`.
 * You should only call `time.ParseDuration` one time and continually reuse the parsed value.
 * Your "statistics" code has [race conditions](https://en.wikipedia.org/wiki/Race_condition). **This is very bad practice and could result in unpredictable bugs**.
   * You can fix this using the `atomic` package, the `sync` package, or a channel. I'd suggest the latter approach. To adopt said approach, you could fire up a "statistics" Goroutine which takes a channel of answers. Once it receives `count` answers, it prints out some statistics. It would then loop this repeatedly. Once you have the statistics Goroutine setup, all of the background bots would simply send their answers to the statistics channel.
   * It might be easier to remove the "statistics" code from this pull request and start a separate one for that, since it looks like that will be more work.

**Comment by unixpickle** [comment]
To help more with the statistics code, here is a general idea of what you'd do:

Global variable for statistics:

```go
var StatisticsChan = make(chan int, 0)
```

Code inside `main` above `wg.Wait()`:

```go
go func() {
  for {
    stats := make([]int, 4)
    for i := 0; i < answerCount; i++ {
      stats[<-StatisticsChan]++
    }
    // Print statistics here from the stats array, like
    fmt.Println("STATS:")
    for i, x := range stats {
      fmt.Println("Question", i, "-", x)
    }
  }
}()
```

Inside `launchConnection` under `quiz.Send(answer)`:

```go
StatisticsChan <- answer
```

**Comment by Arccotangent** [comment]
I was planning to add delays to kahoot-flood, but since kahoot-flood doesn't really do much other than connect, I didn't see the point.

Working on the statistics and delay now.

**Comment by Arccotangent** [comment]
Done.
I've added a new Comet (cometd) dump which may assist in fixing the websocket issue (#29). The protocol appears to have changed.

**Comment by Arccotangent** [comment]
The protocol has indeed changed. Calls to cometd are different now, working on it!

**Comment by unixpickle** [comment]
The whole point of methods, types, functions, etc., is that you do not have to copy and paste code a bunch of times. I notice here that you've copied and pasted code a bunch of times. The kahoot.NewConn() function should automatically get a session token so that the API's user (i.e. *all* these scripts) doesn't have to do it manually every time (and copy and paste code!).

**Comment by unixpickle** [comment]
As a side note, you should not have grouped all of these changes into one pull request. I want to merge your statistics and delay code, but I do not yet want to merge your fixed websocket code since you did not do it in an elegant way. Unfortunately, since you've put all these changes into one pull request, I have no choice but to wait until you fix the problem before I can merge *any* of the changes...

**Comment by Arccotangent** [comment]
So you would like to get a new session token on each connection? Keep in mind these session tokens can be reused.

**Comment by unixpickle** [comment]
Interesting. Can you reuse a session token for multiple connections that are open at the same time? If so, then NewConn() could cache the session token in a private global variable (e.g. `var sessionToken string`). That way the caller who is using `NewConn()` doesn't have to know about the session token machinery that is going on in the background.

Provided we go with the global session token variable, then there are a few more things to consider. If session tokens can expire, say, after 10 minutes, then we should also have a `var sessionTokenTimeout time.Time` which gets set to `time.Now().After(time.Minute*10)` or something whenever we obtain a new session token. Note also that `NewConn()` needs to work from multiple goroutines, so we need some kind of locking mechanism to avoid race conditions like `var sessionTokenLock sync.RWMutex`.

**Comment by unixpickle** [comment]
If you would prefer, I can merge this and make the changes myself to speed things along.

**Comment by Arccotangent** [comment]
Yes, that would be easier for me. You can merge the pull request if you'd like. Besides, you seem to know more about this than I do.

**Pull request merged**
