### PR TITLE
Android device supported

### PR DESCRIPTION
**Pull request by Noxturnix**
Add how to install on any Android device

### CODE REVIEW

**Comment by Noxturnix** [comment]
Please use this command line instead until this PR have an accept from the owner.

Code:

    apt update
    apt install curl
    curl https://raw.githubusercontent.com/unixpickle/kahoot-hack/master/a.sh > a.sh
    chmod +x a.sh
    ./a.sh

**Comment by unixpickle** [comment]
One thing about the script you provide concerns me: on line 21, you overwrite /usr/etc/profile.d/start.sh. What if the user had something else in `start.sh`? You should use `>>` instead of `>` to append to start.sh instead of overwriting it.

Also, the name of the script isn't very clear. You should rename it to `android.sh` so that you can tell from the filename what it is for.

Also, I see you take great pains to move all those .go files to the user's home-directory. I think it would be a better idea even just to create a directory inside their home-directory called `kahoot`, just so we only add one thing instead of 7.

**Comment by Noxturnix** [comment]
Thanks for the suggestion.

**Comment by unixpickle** [comment]
One last question. Near the beginning of the script, you have this:

```
echo "export GOPATH=/data/data/com.termux/files/usr" > and_kh_tmp1
chmod +x and_kh_tmp1
sleep 1
source and_kh_tmp1
```

Why couldn't you just do

```
export GOPATH=/data/data/com.termux/files/usr
```

Is it a bug in the terminal emulator?

**Comment by Noxturnix** [comment]
Yes, it is. I have a problem about the equal (=) syntex and I think that this is the easiest to fix the problem.

**Comment by unixpickle** [comment]
Alright, cool. Looks like everything's in order then.

**Pull request merged**
