### PR TITLE
added kahoot-auto + library - automatic kahoot bot

### PR DESCRIPTION
**Pull request by reteps**
Based off of `kahoot-play`, this automatically selects answers. The `quizid` appears in the URL of every started quiz. I added the program, a library which:
+ gets an access token from email + password to `create.kahoot.it`
+ returns the quiz data
+ parses the quiz data

Notes:
+ this has been testing, but not on quizzes with multiple right answers
+ this only works for **public kahoots**

### CODE REVIEW

**Comment by reteps** [comment]
Tell me your thoughts guys!!!

**Comment by bjorn3** [comment]
Please prompt for the password then you run it, so your password doesnt get saved in your history file.

**Comment by unixpickle** [comment]
Good work.

I'd rather all the code be in `kahoot-auto`, rather than some of it being in `kahoot`. Since the `kahoot` package is meant to be a reusable Kahoot API, I hold it up to a higher standard than I do the scripts. I am fine with pretty much anything being inside one of the scripts, so long as the script kind of works.

If you *do* want to add stuff to the `kahoot` package itself, there are a lot of changes I'd like to see:

 * Go doc comments: All public methods need a doc comment describing what they do. Follow the rules in [Godoc: documenting Go code](https://blog.golang.org/godoc-documenting-go-code), and wrap the comments so no comment line is longer than 60 characters.
 * Proper error handling: methods which can fail should return an `error` as a return argument. The error message should always include the context of the error before a colon, for example "get access token: failed to parse response JSON". Error messages should not start with a capital nor end with a period.
 * Better method names: "ParseData" is too general to describe what it actually does. So is "ReturnData". 
 * No silly comments: see [Coding Without Comments](https://blog.codinghorror.com/coding-without-comments/). A comment like `//make request` is useless; we see from the very next line exactly what you are doing. Superfluous comments cause redundancy, and redundancy can often lead to inconsistency.
 * Run `gofmt` on all of your code.
 * Use concrete types instead of map[string]interface{}. The `json` package can unmarshal into a struct for a reason. A good API should use the Go type system to convey to users exactly what it does.

Like I said, I won't enforce any of the above bullet points if you put all your code into `kahoot-auto` without changing the `kahoot` package. I would like to have some of these APIs in `kahoot` itself, but I'd rather wait and use a polished implementation that will be easy to understand from Godoc and that will not `panic` on error.

**Comment by reteps** [comment]
How's that?

**Comment by unixpickle** [comment]
Making progress, looking better. Here are some new thoughts:

 * All public structs should be documented with a Godoc comment, just like all public functions should.
 * Don't use `Struct` as part of the name of a `struct`.
 * Separate all struct definitions with a single blank line. No `//############################//`.
 * The `UserStruct` and `Token` types should be hidden (i.e. give them a name starting in a lowercase letter). Don't expose any APIs you don't have to. It's best to provide a minimal API.
 * I'm not sure what is up with the import in kahoot-auto. You should import `"github.com/unixpickle/kahoot"`, not `"kahoot"`.
 * `fmt.Scanf("%s")` doesn't read strings with spaces. If my password has spaces, your program won't accept it. Consider using [gopass](https://github.com/howeyc/gopass) -- but since that's in one of the scripts, I'm more lenient about it.

Here is how I would name the structs you currently have (and the docstrings I would use).

 * `ChoiceStruct` -> `QuizChoice` "QuizChoice represents a possible answer for a QuizQuestion."
 * `VideoStruct` -> `QuizVideo` "QuizVideo is an optional video for a QuizQuestion."
 * `QuestionStruct` -> `QuizQuestion` "QuizQuestion is a question in a quiz."
 * `MetadataStruct` -> `QuizMetadata` "QuizMetadata stores metadata about a quiz."
 * `ModerationStruct` -> `QuizModeration` "QuizModeration stores moderator information for a quiz."
 * `KahootQuiz` -> `QuizInfo` "QuizInfo stores information about a quiz, including the correct answers."

**Comment by reteps** [comment]
ok! please evaluate again.

**Comment by reteps** [comment]
yayyy!!!

**Comment by unixpickle** [comment]
Looking good!

**Comment by reteps** [comment]
thanks.

**Pull request merged**
